server:
  port: 8080

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  #type-aliases-package: com.wanxi.pojo
  #开启下划线驼峰命名规则
  configuration:
    map-underscore-to-camel-case: true

#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanxi?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Redis
  redis:
    host: 192.168.78.128
    port: 6379

  #rabbitmq相关的参数配置
  rabbitmq:
    host: 192.168.78.128
    port: 5672
    username: fxf
    password: fxf
    virtual-host: /vm2

  #修改上传文件大小的配置
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  #es配置
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      client:
#        reactive:
#          socket-timeout: 15000
#          endpoints: localhost:9201,localhost:9202,localhost:9203

  #es
  elasticsearch:
    rest:
      uris: localhost:9201,localhost:9202,localhost:9203
      connection-timeout: 10s

# es6的配置方式
#  data:
#    elasticsearch:
#      cluster-name: es_cluster
#      cluster-nodes: localhost:9201,localhost:9202,localhost:9203

